Issue 3.0
DawidSA2017/FeatureIDE pull request #31
Opened 2017-10-09 14:18 UTC by madateamprojekt

Not sure where the mergeconflicts come from.

2017-10-09 14:29 UTC, tthuem commented
Please rerun builds in target travis. Failing tests seem to be performance related and should go through next time.

2017-10-09 14:52 UTC, PaulWestphal requested changes

2017-10-09 14:52 UTC, PaulWestphal commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/base/impl/FeatureAttribute.java
> +		if (type.toString().equals("LONG")) {
Define final Strings for LONG, DOUBLE and BOOLEAN.

2017-10-09 14:52 UTC, PaulWestphal commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/base/impl/FeatureAttribute.java
> +			}
just

return value.toLowerCase().equals("true");

instead

2017-10-09 14:52 UTC, PaulWestphal commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +			if (fa.getName().toLowerCase().equals(attributeName)) {
return fa.getName().toLowerCase().equals(attributeName);

instead

2017-10-09 14:52 UTC, PaulWestphal commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +
unnecessary line break

2017-10-09 14:52 UTC, PaulWestphal commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +				throwError("This attribute has needs a name.", e);
????????????

2017-10-09 14:52 UTC, PaulWestphal commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +		name = name.toLowerCase();
Define names for integers returned by this method.

2017-10-10 09:07 UTC, PaulWestphal requested changes

2017-10-10 09:07 UTC, PaulWestphal commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XmlFeatureModelFormat.java
> +			return (fa.getName().toLowerCase().equals(attributeName));
I was wrong about this, sorry. It now returns true or false immediately, please revert to the original.

2017-10-10 09:07 UTC, PaulWestphal commented on plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/io/xml/XMLFeatureModelTags.java
> +	static final String FEATURE_INHERITED = "feaute inherited";
Consider using enums for this.

2017-10-10 10:17 UTC, PaulWestphal approved these changes

2017-10-10 11:14 UTC, merged